# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Go-linter
    # You may pin to the exact commit or the version.
    # uses: Jerome1337/golint-action@2c695d223ee85ccf25d5e5e150a1b2dbc3fc3634
      uses: Jerome1337/golint-action@v1.0.3
      with:
        # Path used by golint command
        golint-path: .golangci.yml
